### ISSUE TITLE
Jdbc FiberConnection doesn't use Fibers where appropriate

### ISSUE THREAD

**Issue by hsestupin** [puniverse/comsat#27]
Hi, may be I'm misunderstood something. Is there any reason behind that fibers aren't used in every FiberConnection method which throws SQLException exception. For example java.sql.Connection#commit is a blocking method undoubtedly. Why don't we have to wrap it to something like this:

```java
FiberAsync.runBlocking(exec, new CheckedCallable<Void, SQLException>() {

    @Override
    public Void call() throws SQLException {
        return conn.commit();
    }
});

**Comment by circlespainter** [comment]
Thanks for reporting this, I'll look into it very soon. Yes, they should really be fiber-blocking.

**Comment by circlespainter** [comment]
Fixed with [this branch](https://github.com/puniverse/comsat/tree/jdbc-overhaul) that will be merged into master to enter next release.
