### ISSUE TITLE
FiberCloseableHttpAsyncClient is not public visible

### ISSUE THREAD

**Issue by ncliang** [puniverse/comsat#29]
https://github.com/puniverse/comsat/blob/master/comsat-httpclient/src/main/java/co/paralleluniverse/fibers/httpasyncclient/FiberCloseableHttpAsyncClient.java

FiberCloseableHttpAsyncClient is not visible outside of package, so nobody is _really_ able to use it as it is intended to be used as described in the [docs](http://docs.paralleluniverse.co/comsat/#http-clients)

**Comment by circlespainter** [comment]
True, thanks.
