### ISSUE TITLE
Add OkHttp client as option to comsat-retrofit

### ISSUE THREAD

**Issue by azell** [puniverse/comsat#48]
Based on the conclusions from http://blog.paralleluniverse.co/2015/12/02/http-clients/

> OkHttp excels in speed and memory utilization for fast requests. The fiber version for the JVM uses the async API and performs significantly better even though the underlying mechanism is traditional blocking I/O served by a thread pool.

It would be nice to support using OkHttp as a client to comsat-retrofit in addition to Apache HttpClient.  Hopefully most of the hard work has already been implemented in comsat-okhttp.

**Comment by circlespainter** [comment]
Closed with https://github.com/puniverse/comsat/pull/64/commits/acfb31f624db397b9955fe6765cb1a056a7cbf8e. Thanks a lot!
