### ISSUE TITLE
SimpleHttpRequest & SimpleHttpResponse access

### ISSUE THREAD

**Issue by roded** [puniverse/comsat#54]
Hi,
I'm trying to test a `WebActor` by fabricating and sending it `WebMessage`s directly.
`SimpleHttpRequest` & `SimpleHttpResponse` are useful for this purpose but are of `private` access.
Can they be made `public`?

Edit: Actually, `SimpleHttpRequest` is more relevant to the issue. I don't need to create `SimpleHttpResponse`s.

**Comment by circlespainter** [comment]
You should already be able to create a custom `SimpleHttpResponse` by using `HttpResponse.Builder.` (should you need it). And actually it looks to me like an equivalent `build` method is missing in `HttpRequest.Builder`. Would it work for you?

**Comment by roded** [comment]
Yes, that's better.
Thanks

**Comment by circlespainter** [comment]
A new snapshot should be available on SonaType.
