### ISSUE TITLE
AutoWebActorHandler session handling 

### ISSUE THREAD

**Issue by roded** [puniverse/comsat#62]
`AutoWebActorHandler` first creates a session and then tries creating an actor based on the current `HttpServerExchange`.
In cases where the first HTTP path requested it not handled by any defined `WebActor`s (a case which is now possible since the HTTP handlers can be chained), a new session will be created with a null actor reference, leaving the user of the session unable to initiate a `WebActor` even when the requested path should be handled by it (that is, only till the session invalidates).
I think the session should be created only if an actor relevant to the exchange was found.
An easy fix, though not ideal, would be to check the actorRef in `AutoContextProvider` and invalidate the session if no actorRef is found.

**Comment by roded** [comment]
An attempt at a solution: https://github.com/roded/comsat/commit/6412b42304f1f5657d284d74c945eab1146b0ee7

**Comment by circlespainter** [comment]
Looks good, could you create a PR?
