### ISSUE TITLE
WebActorInitializer should not assert on the presence of websockets

### ISSUE THREAD

**Issue by victornoel** [puniverse/comsat#74]
Hi,

For people using web actors without websockets, it is not needed to assert on the presence of websockets in a servlet container, actually, it is a problem if one does not want to enable them!

Maybe the check should be done only in case the `@WebActor` annotation has web socket url patterns?

**Comment by pron** [comment]
Sure, makes sense. Want to submit a PR?

**Comment by victornoel** [comment]
Oh, yeah, no problem, will do :)

**Comment by victornoel** [comment]
And here it is :)

By the way @pron, is there any ETA for the next release of comsat?

**Comment by pron** [comment]
Thanks.
This usually depends on the number of features/bugs and accumulated and their utility/severity. I think we're up for a release very soon.
