### ISSUE TITLE
comsat-tomcat-loader-0.7.0-jdk8.jar not compatible with quasar-core-0.7.6-jdk8.jar

### ISSUE THREAD

**Issue by sheinbergon** [puniverse/comsat#77]
Hi all

it seems that a recent change made to co.paralleluniverse.fibers.instrument.QuasarInstrumentor  ( in 0.7.6 , as version 0.7.5 still works) removed this constructor :

```
    public QuasarInstrumentor(ClassLoader classLoader) {
        this(false, classLoader, new DefaultSuspendableClassifier(classLoader));
    }
```

So now , when trying to activate the tomcat-loader by overriding the loader in META-INF/context.xml , you get a NoSuchMethodException

I know I'm opening this issue in the comsat and not the quasar page , but I aassum comsat/quasar are developed by the same people/company, So I guess it's fine.

**Comment by pron** [comment]
This is already resolved in master and in comsat `0.7.1-SNAPSHOT`.
