### ISSUE TITLE
FiberHttpClient(ApacheHttpClient) with Spring Boot integration test get Error `java.net.SocketException: Too many open files`

### ISSUE THREAD

**Issue by tigerMoon** [puniverse/comsat#79]
Here is the detail code in [Github](https://github.com/tigerMoon/springboot-fiberclient-integration-test)

**Comment by tigerMoon** [comment]
@circlespainter  can you help me .thank you.

**Comment by pron** [comment]
Hi.
Are the requests even running inside fibers? You can test by calling `Fiber.currentFiber()` from within requests. It seems like you haven't enabled fibers in your application at all. See [the documentation](http://docs.paralleluniverse.co/comsat/#spring) for how to do it.

**Comment by tigerMoon** [comment]
than you pron. this is the bug of my configuration of HttpClient.  i had set a large IO thread number . `@Value("${fiber.http.client.io.thread:1000}")`  . which occupies the system resource. 

I have used Comsat and  Quasar in our production for concurrency http request. it`s so cool.

**Comment by pron** [comment]
Glad you've solved this.
